version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/lvlup.db:/app/lvlup.db
      - static_volume:/app/static
    env_file:
      - backend/app/.env
    restart: unless-stopped
    networks:
      - lvlup-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  static_volume:

networks:
  lvlup-network:
    driver: bridge